version: "3"
services:

    redis:
        image: redis
        container_name: redis_standalone
        network_mode: bridge
        restart: always
        tty: true
        ports:
            - 6379:6379
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - /opt/push/redis/standalone:/data
        command: redis-server /data/redis.conf
