version: '3'
services:

    mongo_standalone:
        image: mongo
        container_name: mongo_standalone
        network_mode: bridge
        restart: always
        tty: true
        ports:
            - 27017:27017
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - /opt/push/mongo/standalone/db:/data/db
        command: mongod --noauth --dbpath /data/db
